export default {
  login: "renatomacedo1",
  id: 18704701,
  node_id: "MDQ6VXNlcjE4NzA0NzAx",
  avatar_url: "https://avatars.githubusercontent.com/u/18704701?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/renatomacedo1",
  html_url: "https://github.com/renatomacedo1",
  followers_url: "https://api.github.com/users/renatomacedo1/followers",
  following_url:
    "https://api.github.com/users/renatomacedo1/following{/other_user}",
  gists_url: "https://api.github.com/users/renatomacedo1/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/renatomacedo1/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/renatomacedo1/subscriptions",
  organizations_url: "https://api.github.com/users/renatomacedo1/orgs",
  repos_url: "https://api.github.com/users/renatomacedo1/repos",
  events_url: "https://api.github.com/users/renatomacedo1/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/renatomacedo1/received_events",
  type: "User",
  site_admin: false,
  name: "Renato Macedo",
  company: "Devoteam",
  blog: "",
  location: "Portugal",
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 20,
  public_gists: 0,
  followers: 2,
  following: 5,
  created_at: "2016-04-27T16:39:20Z",
  updated_at: "2022-04-28T14:11:22Z",
};
